package UIs;

import Classes.AccountModel;
import Classes.AutomaticIdGenerator;
import Classes.ProjectDesign;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class AccountSalaryVoucher extends javax.swing.JFrame {

    ProjectDesign pD;
    AutomaticIdGenerator autoId;
    AccountModel aM;

    public AccountSalaryVoucher() throws SQLException {
        initComponents();
        GetCurrentSystemDate();
        this.autoId = new AutomaticIdGenerator();
        jL_VoucherId.setText("SAL-" + (autoId.IdGenerator("AccountSalaryVoucher")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_SalaryInformation = new javax.swing.JPanel();
        jMC_SalaryMonth = new com.toedter.calendar.JMonthChooser();
        jP_SalaryCalculation = new javax.swing.JPanel();
        jTF_ProvidentFund = new javax.swing.JTextField();
        jL_Loan = new javax.swing.JLabel();
        jS_Totals = new javax.swing.JSeparator();
        jL_HRA = new javax.swing.JLabel();
        jT_HRA = new javax.swing.JTextField();
        jTF_TotalEarnings = new javax.swing.JTextField();
        jL_TSDIT = new javax.swing.JLabel();
        jL_Conveyance = new javax.swing.JLabel();
        jL_ProfessionTax = new javax.swing.JLabel();
        jL_ProvidentFund = new javax.swing.JLabel();
        jTF_ESI = new javax.swing.JTextField();
        jTF_NetSalary = new javax.swing.JTextField();
        jL_BasicDA = new javax.swing.JLabel();
        jL_NetSalary = new javax.swing.JLabel();
        jTF_ProfessionTax = new javax.swing.JTextField();
        jT_BasicDA = new javax.swing.JTextField();
        jL_TotalEarnings = new javax.swing.JLabel();
        jTF_ConveyanceAllowance = new javax.swing.JTextField();
        jL_DeducTitle = new javax.swing.JLabel();
        jS_Net = new javax.swing.JSeparator();
        jL_TotalDeduction = new javax.swing.JLabel();
        jL_EarnTitle = new javax.swing.JLabel();
        jTF_TotalDeduction = new javax.swing.JTextField();
        jTF_Loan = new javax.swing.JTextField();
        jTF_TSDIT = new javax.swing.JTextField();
        jL_ESI = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jL_BasicDA1 = new javax.swing.JLabel();
        jL_BasicDA2 = new javax.swing.JLabel();
        jL_BasicDA3 = new javax.swing.JLabel();
        jL_TotalAddition1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jYC_Year = new com.toedter.calendar.JYearChooser();
        jP_LogoAddrs = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jP_PaymentVoucher = new javax.swing.JPanel();
        jL_TeaEmpName = new javax.swing.JLabel();
        jS_VoucherDesignation = new javax.swing.JSeparator();
        jS_VoucherDepartment = new javax.swing.JSeparator();
        jL_VoucherId = new javax.swing.JLabel();
        jL_SalaryVoucher = new javax.swing.JLabel();
        jS_VoucherId = new javax.swing.JSeparator();
        jS_VoucherTeaEmpId = new javax.swing.JSeparator();
        jL_VoucherDate = new javax.swing.JLabel();
        jS_VoucherMain = new javax.swing.JSeparator();
        jS_VoucherDate = new javax.swing.JSeparator();
        jL_TeaEmpDesignationPosition = new javax.swing.JLabel();
        jTF_TeaEmpId = new javax.swing.JTextField();
        jTF_SearchBox = new javax.swing.JTextField();
        jB_Save = new javax.swing.JButton();
        jB_Update = new javax.swing.JButton();
        jB_Delete = new javax.swing.JButton();
        jB_Reload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jP_SalaryInformation.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMC_SalaryMonth.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jP_SalaryCalculation.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jTF_ProvidentFund.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTF_ProvidentFund.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_ProvidentFund.setToolTipText("Basic and Dearness Allowance");
        jTF_ProvidentFund.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTF_ProvidentFundKeyReleased(evt);
            }
        });

        jL_Loan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jL_Loan.setText("Loan");
        jL_Loan.setToolTipText("Conveyance Allowance");

        jS_Totals.setForeground(new java.awt.Color(0, 0, 0));

        jL_HRA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jL_HRA.setText("HRA");
        jL_HRA.setToolTipText("House Rent Allowance (HRA)");

        jT_HRA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jT_HRA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_HRA.setToolTipText("House Rent Allowance (HRA)");

        jTF_TotalEarnings.setEditable(false);
        jTF_TotalEarnings.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTF_TotalEarnings.setForeground(new java.awt.Color(255, 0, 0));
        jTF_TotalEarnings.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_TotalEarnings.setToolTipText("Total Earning");

        jL_TSDIT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jL_TSDIT.setText("TSD/IT");
        jL_TSDIT.setToolTipText("Conveyance Allowance");

        jL_Conveyance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jL_Conveyance.setText("Conveyance Allowance");
        jL_Conveyance.setToolTipText("Conveyance Allowance");

        jL_ProfessionTax.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jL_ProfessionTax.setText("Profession Tax");
        jL_ProfessionTax.setToolTipText("Conveyance Allowance");

        jL_ProvidentFund.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jL_ProvidentFund.setText("Provident Fund");
        jL_ProvidentFund.setToolTipText("Basic and Dearness Allowance");

        jTF_ESI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTF_ESI.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_ESI.setToolTipText("Employee’s State Insurance");
        jTF_ESI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTF_ESIKeyReleased(evt);
            }
        });

        jTF_NetSalary.setEditable(false);
        jTF_NetSalary.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTF_NetSalary.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_NetSalary.setToolTipText("House Rent Allowance");

        jL_BasicDA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jL_BasicDA.setText("Basic & DA");
        jL_BasicDA.setToolTipText("Basic & Dearness Allowance (DA)");

        jL_NetSalary.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jL_NetSalary.setText("Net Salary");
        jL_NetSalary.setToolTipText("Conveyance Allowance");

        jTF_ProfessionTax.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTF_ProfessionTax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_ProfessionTax.setToolTipText("House Rent Allowance");

        jT_BasicDA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jT_BasicDA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_BasicDA.setToolTipText("Basic & Dearness Allowance (DA)");

        jL_TotalEarnings.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jL_TotalEarnings.setText("Total Earning");
        jL_TotalEarnings.setToolTipText("Total Earning");

        jTF_ConveyanceAllowance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTF_ConveyanceAllowance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_ConveyanceAllowance.setToolTipText("Conveyance Allowance");
        jTF_ConveyanceAllowance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTF_ConveyanceAllowanceKeyReleased(evt);
            }
        });

        jL_DeducTitle.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jL_DeducTitle.setText("Deductions");

        jS_Net.setForeground(java.awt.Color.red);

        jL_TotalDeduction.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jL_TotalDeduction.setText("Total Deduction");
        jL_TotalDeduction.setToolTipText("Total Deduction");

        jL_EarnTitle.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jL_EarnTitle.setText("Earnings");

        jTF_TotalDeduction.setEditable(false);
        jTF_TotalDeduction.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTF_TotalDeduction.setForeground(new java.awt.Color(255, 0, 0));
        jTF_TotalDeduction.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_TotalDeduction.setToolTipText("Total Deduction");

        jTF_Loan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTF_Loan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_Loan.setToolTipText("House Rent Allowance");

        jTF_TSDIT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTF_TSDIT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_TSDIT.setToolTipText("House Rent Allowance");
        jTF_TSDIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTF_TSDITKeyReleased(evt);
            }
        });

        jL_ESI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jL_ESI.setText("E.S.I");
        jL_ESI.setToolTipText("Employee’s State Insurance");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("BDT");
        jLabel15.setToolTipText("Bangladeshi Taka");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("BDT");
        jLabel17.setToolTipText("Bangladeshi Taka");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("BDT");
        jLabel18.setToolTipText("Bangladeshi Taka");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("%");
        jLabel19.setToolTipText("Percentage");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("BDT");
        jLabel21.setToolTipText("Bangladeshi Taka");

        jL_BasicDA1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jL_BasicDA1.setText("BDT");
        jL_BasicDA1.setToolTipText("Bangladeshi Taka");

        jL_BasicDA2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jL_BasicDA2.setText("%");
        jL_BasicDA2.setToolTipText("Percentage");

        jL_BasicDA3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jL_BasicDA3.setText("%");
        jL_BasicDA3.setToolTipText("Percentage");

        jL_TotalAddition1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jL_TotalAddition1.setText("BDT");
        jL_TotalAddition1.setToolTipText("Bangladeshi Taka");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("BDT");
        jLabel22.setToolTipText("Bangladeshi Taka");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("BDT");
        jLabel23.setToolTipText("Bangladeshi Taka");

        javax.swing.GroupLayout jP_SalaryCalculationLayout = new javax.swing.GroupLayout(jP_SalaryCalculation);
        jP_SalaryCalculation.setLayout(jP_SalaryCalculationLayout);
        jP_SalaryCalculationLayout.setHorizontalGroup(
            jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SalaryCalculationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jS_Net, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_SalaryCalculationLayout.createSequentialGroup()
                        .addGroup(jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jP_SalaryCalculationLayout.createSequentialGroup()
                                .addGroup(jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jP_SalaryCalculationLayout.createSequentialGroup()
                                        .addComponent(jL_EarnTitle)
                                        .addGap(68, 68, 68))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_SalaryCalculationLayout.createSequentialGroup()
                                        .addGroup(jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jP_SalaryCalculationLayout.createSequentialGroup()
                                                .addComponent(jL_Conveyance)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jL_BasicDA3))
                                            .addGroup(jP_SalaryCalculationLayout.createSequentialGroup()
                                                .addComponent(jL_HRA)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                                                .addComponent(jL_BasicDA2))
                                            .addGroup(jP_SalaryCalculationLayout.createSequentialGroup()
                                                .addComponent(jL_BasicDA)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                                .addComponent(jL_BasicDA1)))
                                        .addGap(4, 4, 4)))
                                .addGroup(jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTF_ConveyanceAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jT_HRA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jT_BasicDA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jP_SalaryCalculationLayout.createSequentialGroup()
                                .addComponent(jL_TotalEarnings)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jL_TotalAddition1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_TotalEarnings, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addGroup(jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jP_SalaryCalculationLayout.createSequentialGroup()
                                .addComponent(jL_ProfessionTax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_ProfessionTax, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP_SalaryCalculationLayout.createSequentialGroup()
                                .addGroup(jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jP_SalaryCalculationLayout.createSequentialGroup()
                                        .addComponent(jL_ESI)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17))
                                    .addGroup(jP_SalaryCalculationLayout.createSequentialGroup()
                                        .addComponent(jL_ProvidentFund)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15))
                                    .addGroup(jP_SalaryCalculationLayout.createSequentialGroup()
                                        .addComponent(jL_Loan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTF_Loan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTF_ESI, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTF_ProvidentFund, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jP_SalaryCalculationLayout.createSequentialGroup()
                                .addComponent(jL_TSDIT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_TSDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jP_SalaryCalculationLayout.createSequentialGroup()
                                .addComponent(jL_TotalDeduction)
                                .addGap(105, 105, 105)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTF_TotalDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jL_DeducTitle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jP_SalaryCalculationLayout.createSequentialGroup()
                                .addComponent(jL_NetSalary)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_NetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jS_Totals))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_SalaryCalculationLayout.setVerticalGroup(
            jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SalaryCalculationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_EarnTitle)
                    .addComponent(jL_DeducTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jL_BasicDA)
                    .addComponent(jT_BasicDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_ProvidentFund)
                    .addComponent(jTF_ProvidentFund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jL_BasicDA1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jL_HRA)
                    .addComponent(jT_HRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_ESI)
                    .addComponent(jTF_ESI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jL_BasicDA2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jL_Conveyance)
                    .addComponent(jTF_ConveyanceAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Loan)
                    .addComponent(jTF_Loan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jL_BasicDA3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jL_ProfessionTax)
                    .addComponent(jTF_ProfessionTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jL_TSDIT)
                    .addComponent(jTF_TSDIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(10, 10, 10)
                .addComponent(jS_Totals, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jL_TotalEarnings)
                    .addComponent(jTF_TotalEarnings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_TotalDeduction)
                    .addComponent(jTF_TotalDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_TotalAddition1)
                    .addComponent(jLabel22))
                .addGap(10, 10, 10)
                .addComponent(jS_Net, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jP_SalaryCalculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jL_NetSalary)
                    .addComponent(jTF_NetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap())
        );

        jS_Net.getAccessibleContext().setAccessibleName("");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("and Year:");
        jLabel2.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Salary Allocation for - Month:");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jP_SalaryInformationLayout = new javax.swing.GroupLayout(jP_SalaryInformation);
        jP_SalaryInformation.setLayout(jP_SalaryInformationLayout);
        jP_SalaryInformationLayout.setHorizontalGroup(
            jP_SalaryInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SalaryInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_SalaryInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_SalaryInformationLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(jMC_SalaryMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(jYC_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jP_SalaryCalculation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jP_SalaryInformationLayout.setVerticalGroup(
            jP_SalaryInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SalaryInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_SalaryInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jMC_SalaryMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jYC_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jP_SalaryCalculation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jP_LogoAddrs.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Email: example@email.com");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("School address goes here");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/School Logo Large.png"))); // NOI18N
        jLabel4.setToolTipText("School Logo");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("City, State, zip code");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tel: 122-455-7788 | Fax: 444-555-6666");

        javax.swing.GroupLayout jP_LogoAddrsLayout = new javax.swing.GroupLayout(jP_LogoAddrs);
        jP_LogoAddrs.setLayout(jP_LogoAddrsLayout);
        jP_LogoAddrsLayout.setHorizontalGroup(
            jP_LogoAddrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_LogoAddrsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jP_LogoAddrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel20))
                .addContainerGap())
        );
        jP_LogoAddrsLayout.setVerticalGroup(
            jP_LogoAddrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_LogoAddrsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_LogoAddrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jP_LogoAddrsLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20)))
                .addContainerGap())
        );

        jP_PaymentVoucher.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jL_TeaEmpName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_TeaEmpName.setText("Teacher Name / Employee Name");

        jS_VoucherDesignation.setForeground(new java.awt.Color(0, 0, 0));

        jS_VoucherDepartment.setForeground(new java.awt.Color(0, 0, 0));

        jL_VoucherId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jL_VoucherId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_VoucherId.setText("Salary Id");

        jL_SalaryVoucher.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_SalaryVoucher.setText("SALARY VOUCHER");

        jS_VoucherId.setForeground(new java.awt.Color(0, 0, 0));

        jS_VoucherTeaEmpId.setForeground(new java.awt.Color(0, 0, 0));

        jL_VoucherDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jL_VoucherDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_VoucherDate.setText("Salary Date");

        jS_VoucherMain.setForeground(java.awt.Color.red);

        jS_VoucherDate.setForeground(new java.awt.Color(0, 0, 0));

        jL_TeaEmpDesignationPosition.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_TeaEmpDesignationPosition.setText("Teacher Designation / Employee Position");

        jTF_TeaEmpId.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_TeaEmpId.setText("Teacher or Employee Id");
        jTF_TeaEmpId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTF_TeaEmpIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTF_TeaEmpIdFocusLost(evt);
            }
        });
        jTF_TeaEmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_TeaEmpIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_PaymentVoucherLayout = new javax.swing.GroupLayout(jP_PaymentVoucher);
        jP_PaymentVoucher.setLayout(jP_PaymentVoucherLayout);
        jP_PaymentVoucherLayout.setHorizontalGroup(
            jP_PaymentVoucherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_PaymentVoucherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_PaymentVoucherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jS_VoucherTeaEmpId)
                    .addComponent(jS_VoucherDesignation)
                    .addComponent(jS_VoucherDepartment)
                    .addComponent(jS_VoucherId)
                    .addComponent(jS_VoucherMain, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jS_VoucherDate)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jP_PaymentVoucherLayout.createSequentialGroup()
                        .addComponent(jL_SalaryVoucher)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jP_PaymentVoucherLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jP_PaymentVoucherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_VoucherDate)
                            .addComponent(jL_VoucherId)
                            .addComponent(jL_TeaEmpName)))
                    .addComponent(jTF_TeaEmpId))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_PaymentVoucherLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_TeaEmpDesignationPosition)
                .addGap(6, 6, 6))
        );
        jP_PaymentVoucherLayout.setVerticalGroup(
            jP_PaymentVoucherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_PaymentVoucherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_SalaryVoucher)
                .addGap(5, 5, 5)
                .addComponent(jS_VoucherMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_VoucherDate)
                .addGap(5, 5, 5)
                .addComponent(jS_VoucherDate, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jL_VoucherId)
                .addGap(5, 5, 5)
                .addComponent(jS_VoucherId, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jTF_TeaEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jS_VoucherTeaEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jL_TeaEmpName)
                .addGap(5, 5, 5)
                .addComponent(jS_VoucherDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jL_TeaEmpDesignationPosition)
                .addGap(5, 5, 5)
                .addComponent(jS_VoucherDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jS_VoucherDate.getAccessibleContext().setAccessibleName("");

        jTF_SearchBox.setBackground(new java.awt.Color(255, 153, 153));
        jTF_SearchBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTF_SearchBox.setText("Search by Salary Id...");
        jTF_SearchBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTF_SearchBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTF_SearchBoxFocusLost(evt);
            }
        });
        jTF_SearchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_SearchBoxActionPerformed(evt);
            }
        });

        jB_Save.setFont(new java.awt.Font("Lucida Calligraphy", 0, 11)); // NOI18N
        jB_Save.setText("Save");
        jB_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SaveActionPerformed(evt);
            }
        });

        jB_Update.setFont(new java.awt.Font("Lucida Calligraphy", 0, 11)); // NOI18N
        jB_Update.setText("Update");
        jB_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_UpdateActionPerformed(evt);
            }
        });

        jB_Delete.setFont(new java.awt.Font("Lucida Calligraphy", 0, 11)); // NOI18N
        jB_Delete.setText("Delete");
        jB_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_DeleteActionPerformed(evt);
            }
        });

        jB_Reload.setFont(new java.awt.Font("Lucida Calligraphy", 0, 11)); // NOI18N
        jB_Reload.setText("Reload");
        jB_Reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jB_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274)
                        .addComponent(jB_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jP_SalaryInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jP_LogoAddrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTF_SearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB_Reload, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jP_PaymentVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jP_LogoAddrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_SearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jB_Reload)
                        .addComponent(jP_PaymentVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jP_SalaryInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Save)
                    .addComponent(jB_Update)
                    .addComponent(jB_Delete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GetBothEmpTea() {
        String sqlString = "", feedBack = "";
        try {
            aM = new AccountModel();
            if (jTF_TeaEmpId.getText().toUpperCase().substring(0, 3).equals("EMP")) {
                sqlString = "SELECT EMPID, EMPNAME, EMPPOSITION FROM EMPLOYEEDATASET WHERE EMPID = ?";
            } else if (jTF_TeaEmpId.getText().toUpperCase().substring(0, 3).equals("TEA")) {
                sqlString = "SELECT TEAID, TEANAME, TEADESIGNATION FROM TEACHERDATASET WHERE TEAID = ?";
            }
            aM.SearchBoxId = jTF_TeaEmpId.getText().toUpperCase();
            feedBack = aM.SearchTeacherOrEmployee(sqlString);
            if ("Information Retrive".equals(feedBack)) {
                jTF_TeaEmpId.setText(aM.Id);
                jL_TeaEmpName.setText(aM.Name);
                jL_TeaEmpDesignationPosition.setText(aM.Position_Designation);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AccountSalaryVoucher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void GetCurrentSystemDate() {
        Date date = new Date();
        String strDateFormat = "yyyy-MM-dd";
        DateFormat dateFormat = new SimpleDateFormat(strDateFormat);
        String formattedDate = dateFormat.format(date);
        jL_VoucherDate.setText(formattedDate);
    }

    private void RefreshSalaryVoucher() {
        jL_VoucherId.setText("SAL-" + (autoId.IdGenerator("AccountSalaryVoucher")));
        jL_VoucherDate.setText("Salary Date");
        pD = new ProjectDesign();
        pD.phTextField = jTF_TeaEmpId;
        pD.phTextField.setText("");
        pD.placeHolder("jTextField", "FL", "Teacher or Employee Id");
        pD.phTextField = jTF_SearchBox;
        pD.phTextField.setText("");
        pD.placeHolder("jTextField", "FL", "Search by Salary Id...");
        jL_TeaEmpName.setText("Teacher Name / Employee Name");
        jL_TeaEmpDesignationPosition.setText("Teacher Designation / Employee Position");
        jT_BasicDA.setText("");
        jT_HRA.setText("");
        jTF_ConveyanceAllowance.setText("");
        jTF_TotalEarnings.setText("");
        jTF_ProvidentFund.setText("");
        jTF_ESI.setText("");
        jTF_Loan.setText("");
        jTF_ProfessionTax.setText("");
        jTF_TSDIT.setText("");
        jTF_TotalDeduction.setText("");
        jTF_NetSalary.setText("");
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void jTF_TeaEmpIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_TeaEmpIdFocusGained
        pD = new ProjectDesign();
        pD.phTextField = jTF_TeaEmpId;
        pD.placeHolder("jTextField", "FG", "Teacher or Employee Id");
    }//GEN-LAST:event_jTF_TeaEmpIdFocusGained

    private void jTF_TeaEmpIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_TeaEmpIdFocusLost
        pD = new ProjectDesign();
        pD.phTextField = jTF_TeaEmpId;
        pD.placeHolder("jTextField", "FL", "Teacher or Employee Id");
    }//GEN-LAST:event_jTF_TeaEmpIdFocusLost

    private void jTF_ConveyanceAllowanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_ConveyanceAllowanceKeyReleased
        double basicDA = Double.parseDouble(jT_BasicDA.getText());
        double hRA = Double.parseDouble(jT_HRA.getText());
        double conveyanceAllowance = Double.parseDouble(jTF_ConveyanceAllowance.getText());
        double wholePercentAmount = (basicDA * hRA / 100) + (basicDA * conveyanceAllowance / 100);
        double totalEarnings = basicDA + wholePercentAmount;
        jTF_TotalEarnings.setText(totalEarnings + "");
    }//GEN-LAST:event_jTF_ConveyanceAllowanceKeyReleased

    private void jTF_TSDITKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_TSDITKeyReleased
        jTF_TotalDeduction.setText("");
        jTF_NetSalary.setText("");
        
        double totalEarnings = Double.parseDouble(jTF_TotalEarnings.getText());
        double providentFund = Double.parseDouble(jTF_ProvidentFund.getText());
        double eSI = Double.parseDouble(jTF_ESI.getText());
        double loan = Double.parseDouble(jTF_Loan.getText());
        double professionTax = Double.parseDouble(jTF_ProfessionTax.getText());
        double tSDIT = Double.parseDouble(jTF_TSDIT.getText());
        double totalDeduction = (providentFund - eSI - loan - (totalEarnings * professionTax / 100) - tSDIT);
        jTF_TotalDeduction.setText(totalDeduction + "");
        double netSalary = totalEarnings + totalDeduction;
        jTF_NetSalary.setText(netSalary + "");
    }//GEN-LAST:event_jTF_TSDITKeyReleased

    private void jTF_ProvidentFundKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_ProvidentFundKeyReleased
        if (jTF_TotalEarnings.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "You Have To Figure Out \"Total Earnings Amount\" First.");
            jTF_ProvidentFund.setText("");
        }
    }//GEN-LAST:event_jTF_ProvidentFundKeyReleased

    private void jTF_ESIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_ESIKeyReleased
        if (jTF_TotalEarnings.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "You Have To Figure Out \"Total Earnings Amount\" First.");
            jTF_ESI.setText("");
        }
    }//GEN-LAST:event_jTF_ESIKeyReleased

    private void jB_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SaveActionPerformed
        try {
            String sqlString = "INSERT INTO SALARYACCOUNT(SALID, SALDATE, SALTEAEMPID, SALMONTH, SALYEAR, SALBASICDA, SALHRA, "
                    + "SALCA, SALTOTALEARN, SALFUND, SALESI, SALLOAN, SALPROFTAX, SALTSDIT, SALTOTALDEDUCT, SALNETSALARY) "
                    + "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            aM = new AccountModel();
            aM.Id = jL_VoucherId.getText().toUpperCase();
            aM.Date = jL_VoucherDate.getText();
            aM.TeaEmpId = jTF_TeaEmpId.getText();
            aM.MonthName = jMC_SalaryMonth.getMonth() + "";
            aM.YearName = jYC_Year.getYear() + "";
            aM.BasicDa = jT_BasicDA.getText();
            aM.HRA = jT_HRA.getText();
            aM.ConveyanceAllowance = jTF_ConveyanceAllowance.getText();
            aM.TotalEarning = jTF_TotalEarnings.getText();
            aM.ProvidentFund = jTF_ProvidentFund.getText();
            aM.ESI = jTF_ESI.getText();
            aM.Loan = jTF_Loan.getText();
            aM.ProfessionTax = jTF_ProfessionTax.getText();
            aM.TSDIT = jTF_TSDIT.getText();
            aM.TotalDeduction = jTF_TotalDeduction.getText();
            aM.NetSalary = jTF_NetSalary.getText();
            String feedBack = aM.SalaryVoucherValidityCheck();
            if ("Checked!!!".equals(feedBack)) {
                feedBack = aM.SaveUpdateSalaryVoucher(sqlString, "Save");
            }
            JOptionPane.showMessageDialog(this, feedBack);
            RefreshSalaryVoucher();
        } catch (SQLException ex) {
            Logger.getLogger(AccountSalaryVoucher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jB_SaveActionPerformed

    private void jB_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_UpdateActionPerformed
        try {
            String sqlString = "UPDATE SALARYACCOUNT SET SALID=?, SALDATE=?, SALTEAEMPID=?, SALMONTH=?, SALYEAR=?, SALBASICDA=?, SALHRA=?,"
                    + "SALCA=?, SALTOTALEARN=?, SALFUND=?, SALESI=?, SALLOAN=?, SALPROFTAX=?, SALTSDIT=?, SALTOTALDEDUCT=?, SALNETSALARY=?"
                    + "WHERE SALID=?";
            aM = new AccountModel();
            aM.Id = jL_VoucherId.getText().toUpperCase();
            aM.Date = jL_VoucherDate.getText();
            aM.TeaEmpId = jTF_TeaEmpId.getText();
            aM.MonthName = jMC_SalaryMonth.getMonth() + "";
            aM.YearName = jYC_Year.getYear() + "";
            aM.BasicDa = jT_BasicDA.getText();
            aM.HRA = jT_HRA.getText();
            aM.ConveyanceAllowance = jTF_ConveyanceAllowance.getText();
            aM.TotalEarning = jTF_TotalEarnings.getText();
            aM.ProvidentFund = jTF_ProvidentFund.getText();
            aM.ESI = jTF_ESI.getText();
            aM.Loan = jTF_Loan.getText();
            aM.ProfessionTax = jTF_ProfessionTax.getText();
            aM.TSDIT = jTF_TSDIT.getText();
            aM.TotalDeduction = jTF_TotalDeduction.getText();
            aM.NetSalary = jTF_NetSalary.getText();
            aM.SearchBoxId = jTF_SearchBox.getText().toUpperCase();
            String feedBack = aM.SalaryVoucherValidityCheck();
            if ("Checked!!!".equals(feedBack)) {
                feedBack = aM.SaveUpdateSalaryVoucher(sqlString, "Update");
            }
            JOptionPane.showMessageDialog(this, feedBack);
            RefreshSalaryVoucher();
        } catch (SQLException ex) {
            Logger.getLogger(AccountSalaryVoucher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jB_UpdateActionPerformed

    private void jB_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_DeleteActionPerformed
        try {
            String sqlString = "DELETE FROM SALARYACCOUNT WHERE SALID = ?";
            aM = new AccountModel();
            aM.SearchBoxId = jTF_SearchBox.getText().toUpperCase();
            String feedBack = aM.DeleteSalaryVoucher(sqlString);
            JOptionPane.showMessageDialog(this, feedBack);
            RefreshSalaryVoucher();
        } catch (SQLException ex) {
            Logger.getLogger(AccountSalaryVoucher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jB_DeleteActionPerformed

    private void jTF_SearchBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_SearchBoxFocusGained
        pD = new ProjectDesign();
        pD.phTextField = jTF_SearchBox;
        pD.placeHolder("jTextField", "FG", "Search by Salary Id...");
    }//GEN-LAST:event_jTF_SearchBoxFocusGained

    private void jTF_SearchBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_SearchBoxFocusLost
        pD = new ProjectDesign();
        pD.phTextField = jTF_SearchBox;
        pD.placeHolder("jTextField", "FL", "Search by Salary Id...");
    }//GEN-LAST:event_jTF_SearchBoxFocusLost

    private void jTF_SearchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_SearchBoxActionPerformed
        try {
            String sqlString = "SELECT * FROM SALARYACCOUNT WHERE SALID = ?";
            aM = new AccountModel();
            aM.SearchBoxId = jTF_SearchBox.getText();
            String feedBack = aM.SearchSalaryVoucher(sqlString);

            if ("All Retrive".equals(feedBack)) {
                jL_VoucherId.setText(aM.Id);
                jL_VoucherDate.setText(aM.Date);
                jTF_TeaEmpId.setText(aM.TeaEmpId);
                jMC_SalaryMonth.setMonth(Integer.parseInt(aM.MonthName));
                jYC_Year.setYear(Integer.parseInt(aM.YearName));
                jT_BasicDA.setText(aM.BasicDa);
                jT_HRA.setText(aM.HRA);
                jTF_ConveyanceAllowance.setText(aM.ConveyanceAllowance);
                jTF_TotalEarnings.setText(aM.TotalEarning);
                jTF_ProvidentFund.setText(aM.ProvidentFund);
                jTF_ESI.setText(aM.ESI);
                jTF_Loan.setText(aM.Loan);
                jTF_ProfessionTax.setText(aM.ProfessionTax);
                jTF_TSDIT.setText(aM.TSDIT);
                jTF_TotalDeduction.setText(aM.TotalDeduction);
                jTF_NetSalary.setText(aM.NetSalary);
            }
            GetBothEmpTea();
        } catch (SQLException ex) {
            Logger.getLogger(AccountSalaryVoucher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTF_SearchBoxActionPerformed

    private void jTF_TeaEmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_TeaEmpIdActionPerformed
        GetBothEmpTea();
    }//GEN-LAST:event_jTF_TeaEmpIdActionPerformed

    private void jB_ReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ReloadActionPerformed
        RefreshSalaryVoucher();
    }//GEN-LAST:event_jB_ReloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountSalaryVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountSalaryVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountSalaryVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountSalaryVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new AccountSalaryVoucher().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(AccountSalaryVoucher.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Delete;
    private javax.swing.JButton jB_Reload;
    private javax.swing.JButton jB_Save;
    private javax.swing.JButton jB_Update;
    private javax.swing.JLabel jL_BasicDA;
    private javax.swing.JLabel jL_BasicDA1;
    private javax.swing.JLabel jL_BasicDA2;
    private javax.swing.JLabel jL_BasicDA3;
    private javax.swing.JLabel jL_Conveyance;
    private javax.swing.JLabel jL_DeducTitle;
    private javax.swing.JLabel jL_ESI;
    private javax.swing.JLabel jL_EarnTitle;
    private javax.swing.JLabel jL_HRA;
    private javax.swing.JLabel jL_Loan;
    private javax.swing.JLabel jL_NetSalary;
    private javax.swing.JLabel jL_ProfessionTax;
    private javax.swing.JLabel jL_ProvidentFund;
    private javax.swing.JLabel jL_SalaryVoucher;
    private javax.swing.JLabel jL_TSDIT;
    private javax.swing.JLabel jL_TeaEmpDesignationPosition;
    private javax.swing.JLabel jL_TeaEmpName;
    private javax.swing.JLabel jL_TotalAddition1;
    private javax.swing.JLabel jL_TotalDeduction;
    private javax.swing.JLabel jL_TotalEarnings;
    private javax.swing.JLabel jL_VoucherDate;
    private javax.swing.JLabel jL_VoucherId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private com.toedter.calendar.JMonthChooser jMC_SalaryMonth;
    private javax.swing.JPanel jP_LogoAddrs;
    private javax.swing.JPanel jP_PaymentVoucher;
    private javax.swing.JPanel jP_SalaryCalculation;
    private javax.swing.JPanel jP_SalaryInformation;
    private javax.swing.JSeparator jS_Net;
    private javax.swing.JSeparator jS_Totals;
    private javax.swing.JSeparator jS_VoucherDate;
    private javax.swing.JSeparator jS_VoucherDepartment;
    private javax.swing.JSeparator jS_VoucherDesignation;
    private javax.swing.JSeparator jS_VoucherId;
    private javax.swing.JSeparator jS_VoucherMain;
    private javax.swing.JSeparator jS_VoucherTeaEmpId;
    private javax.swing.JTextField jTF_ConveyanceAllowance;
    private javax.swing.JTextField jTF_ESI;
    private javax.swing.JTextField jTF_Loan;
    private javax.swing.JTextField jTF_NetSalary;
    private javax.swing.JTextField jTF_ProfessionTax;
    private javax.swing.JTextField jTF_ProvidentFund;
    private javax.swing.JTextField jTF_SearchBox;
    private javax.swing.JTextField jTF_TSDIT;
    private javax.swing.JTextField jTF_TeaEmpId;
    private javax.swing.JTextField jTF_TotalDeduction;
    private javax.swing.JTextField jTF_TotalEarnings;
    private javax.swing.JTextField jT_BasicDA;
    private javax.swing.JTextField jT_HRA;
    private com.toedter.calendar.JYearChooser jYC_Year;
    // End of variables declaration//GEN-END:variables
}