package UIs;

import Classes.AutomaticIdGenerator;
import Classes.LibraryBookModel;
import Classes.ProjectDesign;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class LibraryBookBorrow extends javax.swing.JFrame {

    ProjectDesign pD;
    AutomaticIdGenerator autoId;
    LibraryBookModel profileModel;

    public LibraryBookBorrow() throws SQLException {
        initComponents();

        this.autoId = new AutomaticIdGenerator();
        jT_BorrowId.setText("BRW-" + (autoId.IdGenerator("LibraryBookBorrow")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jP_bookInfo = new javax.swing.JPanel();
        jL_AuthorName = new javax.swing.JLabel();
        jL_BookEdition = new javax.swing.JLabel();
        jL_Publication = new javax.swing.JLabel();
        jL_BookTitle = new javax.swing.JLabel();
        jT_BookId = new javax.swing.JTextField();
        jP_timeTableManagement = new javax.swing.JPanel();
        jP_submitDate = new javax.swing.JPanel();
        jDC_SubmitDate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jP_borrowDate = new javax.swing.JPanel();
        jDC_BorrowDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jL_TotalDayCount = new javax.swing.JLabel();
        jP_studentInfo = new javax.swing.JPanel();
        jL_Class = new javax.swing.JLabel();
        jL_StudentName = new javax.swing.JLabel();
        jL_Major = new javax.swing.JLabel();
        jL_Section = new javax.swing.JLabel();
        jT_StudentId = new javax.swing.JTextField();
        jP_controls = new javax.swing.JPanel();
        jB_Remove = new javax.swing.JButton();
        jB_Save = new javax.swing.JButton();
        jB_Upgrade = new javax.swing.JButton();
        jB_Refresh = new javax.swing.JButton();
        jT_BorrowId = new javax.swing.JTextField();
        jT_SearchBox = new javax.swing.JTextField();
        jL_schoolLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jP_bookInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 51, 0)), "Item That Borrowing", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12), new java.awt.Color(192, 0, 0))); // NOI18N
        jP_bookInfo.setToolTipText("Book Information");

        jL_AuthorName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jL_AuthorName.setText("Author Name...");

        jL_BookEdition.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jL_BookEdition.setText("Book Edition...");

        jL_Publication.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jL_Publication.setText("Publication...");

        jL_BookTitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jL_BookTitle.setText("Book Title...");

        jT_BookId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jT_BookId.setForeground(new java.awt.Color(192, 0, 0));
        jT_BookId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jT_BookId.setText("Enter Book Id...");
        jT_BookId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_BookIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_BookIdFocusLost(evt);
            }
        });
        jT_BookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_BookIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_bookInfoLayout = new javax.swing.GroupLayout(jP_bookInfo);
        jP_bookInfo.setLayout(jP_bookInfoLayout);
        jP_bookInfoLayout.setHorizontalGroup(
            jP_bookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_bookInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_bookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Publication)
                    .addComponent(jL_BookEdition)
                    .addComponent(jL_AuthorName)
                    .addComponent(jL_BookTitle)
                    .addComponent(jT_BookId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jP_bookInfoLayout.setVerticalGroup(
            jP_bookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_bookInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jT_BookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jL_BookTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_AuthorName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_BookEdition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_Publication)
                .addContainerGap())
        );

        jP_timeTableManagement.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 51, 51)), "Time Table Management", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12), new java.awt.Color(192, 0, 0))); // NOI18N

        jP_submitDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Date of Return Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12), new java.awt.Color(192, 0, 0))); // NOI18N

        jDC_SubmitDate.setForeground(new java.awt.Color(192, 0, 0));
        jDC_SubmitDate.setToolTipText("Entry Date");
        jDC_SubmitDate.setDateFormatString("yyyy-MM-dd");
        jDC_SubmitDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(192, 0, 0));
        jLabel10.setText("Submit Date");

        javax.swing.GroupLayout jP_submitDateLayout = new javax.swing.GroupLayout(jP_submitDate);
        jP_submitDate.setLayout(jP_submitDateLayout);
        jP_submitDateLayout.setHorizontalGroup(
            jP_submitDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_submitDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_submitDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDC_SubmitDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap())
        );
        jP_submitDateLayout.setVerticalGroup(
            jP_submitDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_submitDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDC_SubmitDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jP_borrowDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Date of Book Borrowing", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12), new java.awt.Color(192, 0, 0))); // NOI18N

        jDC_BorrowDate.setForeground(new java.awt.Color(192, 0, 0));
        jDC_BorrowDate.setToolTipText("Entry Date");
        jDC_BorrowDate.setDateFormatString("yyyy-MM-dd");
        jDC_BorrowDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(192, 0, 0));
        jLabel9.setText("Borrow Date");

        javax.swing.GroupLayout jP_borrowDateLayout = new javax.swing.GroupLayout(jP_borrowDate);
        jP_borrowDate.setLayout(jP_borrowDateLayout);
        jP_borrowDateLayout.setHorizontalGroup(
            jP_borrowDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_borrowDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_borrowDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDC_BorrowDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap())
        );
        jP_borrowDateLayout.setVerticalGroup(
            jP_borrowDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_borrowDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDC_BorrowDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jL_TotalDayCount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jL_TotalDayCount.setForeground(new java.awt.Color(51, 153, 255));
        jL_TotalDayCount.setText("Click here... to see total day count");
        jL_TotalDayCount.setToolTipText("Days Count");
        jL_TotalDayCount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_TotalDayCountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jP_timeTableManagementLayout = new javax.swing.GroupLayout(jP_timeTableManagement);
        jP_timeTableManagement.setLayout(jP_timeTableManagementLayout);
        jP_timeTableManagementLayout.setHorizontalGroup(
            jP_timeTableManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_timeTableManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_timeTableManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_timeTableManagementLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jL_TotalDayCount)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_timeTableManagementLayout.createSequentialGroup()
                        .addComponent(jP_borrowDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jP_submitDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jP_timeTableManagementLayout.setVerticalGroup(
            jP_timeTableManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_timeTableManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_timeTableManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jP_borrowDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_submitDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jL_TotalDayCount, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jP_studentInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 51, 0)), "Student Who Borrowing", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12), new java.awt.Color(192, 0, 0))); // NOI18N
        jP_studentInfo.setToolTipText("Student Information");

        jL_Class.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jL_Class.setText("Class...");

        jL_StudentName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jL_StudentName.setText("Student Name...");

        jL_Major.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jL_Major.setText("Major...");

        jL_Section.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jL_Section.setText("Section...");

        jT_StudentId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jT_StudentId.setForeground(new java.awt.Color(192, 0, 0));
        jT_StudentId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jT_StudentId.setText("Enter Student Id...");
        jT_StudentId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_StudentIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_StudentIdFocusLost(evt);
            }
        });
        jT_StudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_StudentIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_studentInfoLayout = new javax.swing.GroupLayout(jP_studentInfo);
        jP_studentInfo.setLayout(jP_studentInfoLayout);
        jP_studentInfoLayout.setHorizontalGroup(
            jP_studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_studentInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jT_StudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_StudentName)
                    .addComponent(jL_Class)
                    .addComponent(jL_Section)
                    .addComponent(jL_Major))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jP_studentInfoLayout.setVerticalGroup(
            jP_studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_studentInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jT_StudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jL_StudentName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_Class)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_Section)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_Major)
                .addContainerGap())
        );

        jP_controls.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 51, 51)), "Decision Making", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12), new java.awt.Color(192, 0, 0))); // NOI18N

        jB_Remove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_Remove.setForeground(new java.awt.Color(192, 0, 0));
        jB_Remove.setText("REMOVE");
        jB_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_RemoveActionPerformed(evt);
            }
        });

        jB_Save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_Save.setForeground(new java.awt.Color(192, 0, 0));
        jB_Save.setText("SAVE");
        jB_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SaveActionPerformed(evt);
            }
        });

        jB_Upgrade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_Upgrade.setForeground(new java.awt.Color(192, 0, 0));
        jB_Upgrade.setText("UPGRADE");
        jB_Upgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_UpgradeActionPerformed(evt);
            }
        });

        jB_Refresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_Refresh.setForeground(new java.awt.Color(192, 0, 0));
        jB_Refresh.setText("REFRESH");
        jB_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_RefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_controlsLayout = new javax.swing.GroupLayout(jP_controls);
        jP_controls.setLayout(jP_controlsLayout);
        jP_controlsLayout.setHorizontalGroup(
            jP_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_controlsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jB_Upgrade)
                .addGap(18, 18, 18)
                .addComponent(jB_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jB_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_controlsLayout.setVerticalGroup(
            jP_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_controlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Upgrade)
                    .addComponent(jB_Remove)
                    .addComponent(jB_Save)
                    .addComponent(jB_Refresh))
                .addContainerGap())
        );

        jT_BorrowId.setEditable(false);
        jT_BorrowId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jT_BorrowId.setForeground(new java.awt.Color(192, 0, 0));
        jT_BorrowId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jT_BorrowId.setText("Borrow Id");
        jT_BorrowId.setToolTipText("An unique Id have automatic generate");
        jT_BorrowId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));

        jT_SearchBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jT_SearchBox.setForeground(new java.awt.Color(192, 0, 0));
        jT_SearchBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jT_SearchBox.setText("Search by Borrow Id...");
        jT_SearchBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jT_SearchBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_SearchBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_SearchBoxFocusLost(evt);
            }
        });
        jT_SearchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_SearchBoxActionPerformed(evt);
            }
        });

        jL_schoolLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/School Logo Small.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jP_timeTableManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jP_controls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jL_schoolLogo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jP_bookInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jP_studentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jT_BorrowId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jT_SearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jT_BorrowId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_schoolLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_SearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jP_studentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_bookInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jP_timeTableManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jP_controls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isNumeric(String str) {
        for (char c : str.toCharArray()) {
            if (!Character.isDigit(c)) {
                return false;
            }
        }
        return true;
    }

    private void refreshThisForm() {
        jT_BorrowId.setText("BRW-" + (autoId.IdGenerator("LibraryBookBorrow")));
        pD = new ProjectDesign();
        pD.phTextField = jT_BookId;
        pD.phTextField.setText("");
        pD.placeHolder("jTextField", "FL", "Enter Book Id...");
        jL_BookTitle.setText("Book Title...");
        jL_AuthorName.setText("Author Name...");
        jL_BookEdition.setText("Book Edition...");
        jL_Publication.setText("Publication...");
        pD.phTextField = jT_StudentId;
        pD.phTextField.setText("");
        pD.placeHolder("jTextField", "FL", "Enter Student Id...");
        jL_StudentName.setText("Student Name...");
        jL_Class.setText("Class...");
        jL_Section.setText("Section...");
        jL_Major.setText("Major...");
        ((JTextField) jDC_BorrowDate.getDateEditor().getUiComponent()).setText("");
        ((JTextField) jDC_SubmitDate.getDateEditor().getUiComponent()).setText("");
        jL_TotalDayCount.setText("Click here... to see total day count");
        pD.phTextField = jT_SearchBox;
        pD.phTextField.setText("");
        pD.placeHolder("jTextField", "FL", "Search by Borrow Id...");
    }
    
    private void RetrivingBookData() throws SQLException {
        String sqlString = "SELECT * FROM BOOKDATASET WHERE BOKID = ?";
        profileModel = new LibraryBookModel();
        profileModel.SearchId = jT_BookId.getText().toUpperCase();
        String feedBack = profileModel.GetBookDataFromDb(sqlString);
        if ("All Retrive".equals(feedBack)) {
            jT_BookId.setText(profileModel.BId);
            jL_BookTitle.setText("Title: " + profileModel.Name);
            jL_AuthorName.setText("Author: " + profileModel.Author);
            jL_BookEdition.setText("Edition: " + profileModel.Edition);
            jL_Publication.setText("Publication: " + profileModel.Publication);
        }
    }
    
    private void RetrivingStudentData() throws SQLException {
        String sqlString = "SELECT * FROM STUDENTDATASET WHERE STUID = ?";
        profileModel = new LibraryBookModel();
        profileModel.SearchId = jT_StudentId.getText().toUpperCase();
        String feedBack = profileModel.GetStudentDataFromDb(sqlString);
        if ("All Retrive".equals(feedBack)) {
            jT_StudentId.setText(profileModel.SId);
            jL_StudentName.setText("Name: " + profileModel.Name);
            jL_Class.setText("Class: " + profileModel.Class);
            jL_Section.setText("Section: " + profileModel.Section);
            jL_Major.setText("Major: " + profileModel.Major);
        }
    }

    private void jT_BookIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_BookIdFocusGained
        pD = new ProjectDesign();
        pD.phTextField = jT_BookId;
        pD.placeHolder("jTextField", "FG", "Enter Book Id...");
    }//GEN-LAST:event_jT_BookIdFocusGained

    private void jT_BookIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_BookIdFocusLost
        if (jT_BookId.getText().equals("")) {
            pD = new ProjectDesign();
            pD.phTextField = jT_BookId;
            pD.placeHolder("jTextField", "FL", "Enter Book Id...");
        }
    }//GEN-LAST:event_jT_BookIdFocusLost

    private void jT_StudentIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_StudentIdFocusGained
        pD = new ProjectDesign();
        pD.phTextField = jT_StudentId;
        pD.placeHolder("jTextField", "FG", "Enter Student Id...");
    }//GEN-LAST:event_jT_StudentIdFocusGained

    private void jT_StudentIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_StudentIdFocusLost
        if (jT_StudentId.getText().equals("")) {
            pD = new ProjectDesign();
            pD.phTextField = jT_StudentId;
            pD.placeHolder("jTextField", "FL", "Enter Student Id...");
        }
    }//GEN-LAST:event_jT_StudentIdFocusLost

    private void jT_SearchBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_SearchBoxFocusGained
        pD = new ProjectDesign();
        pD.phTextField = jT_SearchBox;
        pD.placeHolder("jTextField", "FG", "Search by Borrow Id...");
    }//GEN-LAST:event_jT_SearchBoxFocusGained

    private void jT_SearchBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_SearchBoxFocusLost
        if (jT_SearchBox.getText().equals("")) {
            pD = new ProjectDesign();
            pD.phTextField = jT_SearchBox;
            pD.placeHolder("jTextField", "FL", "Search by Borrow Id...");
        }
    }//GEN-LAST:event_jT_SearchBoxFocusLost

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        pD = new ProjectDesign();
        if ((jDC_BorrowDate.getDate() != null) || (jDC_SubmitDate.getDate() != null)) {
            pD.phJDateChooser = jDC_BorrowDate;
            pD.phJPanel = jP_borrowDate;
            pD.placeHolder("jDateChooser", "FG", "BorrowDate");

            pD.phJDateChooser = jDC_SubmitDate;
            pD.phJPanel = jP_submitDate;
            pD.placeHolder("jDateChooser", "FG", "SubmitDate");
        } else {
            pD.phJDateChooser = jDC_BorrowDate;
            pD.phJPanel = jP_borrowDate;
            pD.placeHolder("jDateChooser", "FL", "BorrowDate");

            pD.phJDateChooser = jDC_SubmitDate;
            pD.phJPanel = jP_submitDate;
            pD.placeHolder("jDateChooser", "FL", "SubmitDate");
        }
    }//GEN-LAST:event_formMouseClicked

    private void jT_BookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_BookIdActionPerformed
        try {
            RetrivingBookData();
        } catch (SQLException ex) {
            Logger.getLogger(LibraryBookBorrow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jT_BookIdActionPerformed

    private void jT_StudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_StudentIdActionPerformed
        try {
            RetrivingStudentData();
        } catch (SQLException ex) {
            Logger.getLogger(LibraryBookBorrow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jT_StudentIdActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void jL_TotalDayCountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_TotalDayCountMouseClicked
        jL_TotalDayCount.setText(null);
        long diffDateValue = jDC_SubmitDate.getDate().getTime() - jDC_BorrowDate.getDate().getTime();
        jL_TotalDayCount.setText("Total days: " + TimeUnit.DAYS.convert(diffDateValue, TimeUnit.MILLISECONDS));
    }//GEN-LAST:event_jL_TotalDayCountMouseClicked

    private void jB_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SaveActionPerformed
        try {
            String sqlString = "INSERT INTO BOOKBORROWINFO(BRWID, BRWBOKID, BRWSTUID, BRWDATE, "
                    + "BRWSUBDATE, BRWDAYS) VALUES(?,?,?,?,?,?)";
            profileModel = new LibraryBookModel();
            profileModel.Id = jT_BorrowId.getText().toUpperCase();
            profileModel.BId = jT_BookId.getText().toUpperCase();
            profileModel.SId = jT_StudentId.getText().toUpperCase();
            profileModel.BorrowDate = ((JTextField) jDC_BorrowDate.getDateEditor().getUiComponent()).getText();
            profileModel.SubmitDate = ((JTextField) jDC_SubmitDate.getDateEditor().getUiComponent()).getText();
            profileModel.DayCount = jL_TotalDayCount.getText().substring(12);
            String feedBack = profileModel.BookBorrowValidityCheck();
            if ("Checked!!!".equals(feedBack)) {
                feedBack = profileModel.SaveBorrowDetails(sqlString);
            }
            JOptionPane.showMessageDialog(this, feedBack);
            refreshThisForm();
        } catch (SQLException ex) {
            Logger.getLogger(LibraryBookBorrow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jB_SaveActionPerformed

    private void jB_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_RefreshActionPerformed
        refreshThisForm();
    }//GEN-LAST:event_jB_RefreshActionPerformed

    private void jB_UpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_UpgradeActionPerformed
        try {
            String sqlString = "UPDATE BOOKBORROWINFO SET BRWID = ?, BRWBOKID = ?, BRWSTUID = ?, BRWDATE = ?,"
                    + "BRWSUBDATE = ?, BRWDAYS = ? WHERE BRWID = ?";
            profileModel = new LibraryBookModel();
            profileModel.Id = jT_BorrowId.getText().toUpperCase();
            profileModel.BId = jT_BookId.getText().toUpperCase();
            profileModel.SId = jT_StudentId.getText().toUpperCase();
            profileModel.BorrowDate = ((JTextField) jDC_BorrowDate.getDateEditor().getUiComponent()).getText();
            profileModel.SubmitDate = ((JTextField) jDC_SubmitDate.getDateEditor().getUiComponent()).getText();
            profileModel.DayCount = jL_TotalDayCount.getText().substring(12);

            profileModel.SearchId = jT_SearchBox.getText().toUpperCase();

            String feedBack = profileModel.BookAddValidityCheck();
            if ("Checked!!!".equals(feedBack)) {
                feedBack = profileModel.UpgradeBorrowDetails(sqlString);
            }
            JOptionPane.showMessageDialog(this, feedBack);
            refreshThisForm();
        } catch (SQLException ex) {
            Logger.getLogger(LibraryBookBorrow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jB_UpgradeActionPerformed

    private void jT_SearchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_SearchBoxActionPerformed
        try {
            String sqlString = "SELECT * FROM BOOKBORROWINFO WHERE BRWID = ?";

            profileModel = new LibraryBookModel();
            profileModel.SearchId = jT_SearchBox.getText().toUpperCase();
            String feedBack = profileModel.SearchBorrowDetails(sqlString);
            if ("All Retrive".equals(feedBack)) {
                jT_BorrowId.setText(profileModel.Id);
                jT_BookId.setText(profileModel.BId);
                jT_StudentId.setText(profileModel.SId);
                jDC_BorrowDate.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(profileModel.BorrowDate));
                jDC_SubmitDate.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(profileModel.SubmitDate));
                jL_TotalDayCount.setText("Total days: " + profileModel.DayCount);
            }

            /* Get All Required Book Information Via Book Id */
            RetrivingBookData();

            /* Get All Required Student Information Via Student Id */
            RetrivingStudentData();
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(LibraryBookBorrow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jT_SearchBoxActionPerformed

    private void jB_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_RemoveActionPerformed
        try {
            String sqlString = "DELETE FROM BOOKBORROWINFO WHERE BRWID = ?";
            profileModel = new LibraryBookModel();
            profileModel.SearchId = jT_SearchBox.getText().toUpperCase();
            String feedBack = profileModel.DeleteBorrowDetails(sqlString);
            JOptionPane.showMessageDialog(this, feedBack);
            refreshThisForm();
        } catch (SQLException ex) {
            Logger.getLogger(LibraryBookBorrow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jB_RemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryBookBorrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new LibraryBookBorrow().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(LibraryBookBorrow.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Refresh;
    private javax.swing.JButton jB_Remove;
    private javax.swing.JButton jB_Save;
    private javax.swing.JButton jB_Upgrade;
    private com.toedter.calendar.JDateChooser jDC_BorrowDate;
    private com.toedter.calendar.JDateChooser jDC_SubmitDate;
    private javax.swing.JLabel jL_AuthorName;
    private javax.swing.JLabel jL_BookEdition;
    private javax.swing.JLabel jL_BookTitle;
    private javax.swing.JLabel jL_Class;
    private javax.swing.JLabel jL_Major;
    private javax.swing.JLabel jL_Publication;
    private javax.swing.JLabel jL_Section;
    private javax.swing.JLabel jL_StudentName;
    private javax.swing.JLabel jL_TotalDayCount;
    private javax.swing.JLabel jL_schoolLogo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jP_bookInfo;
    private javax.swing.JPanel jP_borrowDate;
    private javax.swing.JPanel jP_controls;
    private javax.swing.JPanel jP_studentInfo;
    private javax.swing.JPanel jP_submitDate;
    private javax.swing.JPanel jP_timeTableManagement;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jT_BookId;
    private javax.swing.JTextField jT_BorrowId;
    private javax.swing.JTextField jT_SearchBox;
    private javax.swing.JTextField jT_StudentId;
    // End of variables declaration//GEN-END:variables
}
