package UIs;

import Classes.UserModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class UserLogIns extends javax.swing.JFrame {
    UserModel usrModel;

    public UserLogIns() throws SQLException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_signIN = new javax.swing.JButton();
        jB_RESET = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jL_userName = new javax.swing.JLabel();
        jL_userPassword = new javax.swing.JLabel();
        jC_userRole = new javax.swing.JComboBox<>();
        jL_userRole = new javax.swing.JLabel();
        jT_userName = new javax.swing.JTextField();
        jP_userPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jL_logINForm = new javax.swing.JLabel();
        jL_schoolLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jB_signIN.setFont(new java.awt.Font("Tempus Sans ITC", 0, 15)); // NOI18N
        jB_signIN.setText("SIGN IN");
        jB_signIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_signINActionPerformed(evt);
            }
        });

        jB_RESET.setFont(new java.awt.Font("Tempus Sans ITC", 0, 15)); // NOI18N
        jB_RESET.setText("RESET");
        jB_RESET.setPreferredSize(new java.awt.Dimension(87, 29));
        jB_RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_RESETActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Log-Ins"));

        jL_userName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jL_userName.setText("USER NAME");

        jL_userPassword.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jL_userPassword.setText("PASSWORD");

        jC_userRole.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jC_userRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Administrator", "Teacher", "Employee", "Librarian" }));

        jL_userRole.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jL_userRole.setText("USER ROLE");

        jT_userName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jP_userPassword.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jL_userName)
                        .addComponent(jL_userPassword))
                    .addComponent(jL_userRole, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jT_userName)
                    .addComponent(jC_userRole, 0, 250, Short.MAX_VALUE)
                    .addComponent(jP_userPassword))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jL_userName)
                    .addComponent(jT_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_userPassword)
                    .addComponent(jP_userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jC_userRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_userRole))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jL_logINForm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jL_logINForm.setText("Let The Privileged User An Entry Ticket");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_logINForm)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_logINForm)
                .addContainerGap())
        );

        jL_schoolLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/School Logo Large.png"))); // NOI18N
        jL_schoolLogo.setText("LOGO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jL_schoolLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jB_signIN)
                        .addGap(92, 92, 92)
                        .addComponent(jB_RESET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_schoolLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_signIN)
                    .addComponent(jB_RESET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_signINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_signINActionPerformed
        try {
            String sqlString = "SELECT * FROM USERDATASET WHERE USRNAME=? AND USRPASSWD=? AND USRROLE=?";
            usrModel = new UserModel();
            usrModel.Name = jT_userName.getText().toUpperCase();
            usrModel.Password = jP_userPassword.getText();
            usrModel.Role = jC_userRole.getSelectedItem().toString().toUpperCase();
            if ("Checked!!!".equals(usrModel.ValidityCheck())) {
                String feedBack = usrModel.SearchLogInsData(sqlString);
                if (feedBack.equals("Information Exist")) {
                    UserFrontPage uFP = new UserFrontPage();
                    uFP.SetUserPermission(usrModel.Role);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, feedBack);
                }
            } else {
                JOptionPane.showMessageDialog(this, "DIDN'T YOU FORGOT SOMETHING TO FILL.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserLogIns.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jB_signINActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void jB_RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_RESETActionPerformed
        jT_userName.setText("");
        jP_userPassword.setText("");
        jC_userRole.setSelectedItem("<Select>");
    }//GEN-LAST:event_jB_RESETActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogIns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogIns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogIns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogIns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UserLogIns().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(UserLogIns.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_RESET;
    private javax.swing.JButton jB_signIN;
    public javax.swing.JComboBox<String> jC_userRole;
    private javax.swing.JLabel jL_logINForm;
    private javax.swing.JLabel jL_schoolLogo;
    private javax.swing.JLabel jL_userName;
    private javax.swing.JLabel jL_userPassword;
    private javax.swing.JLabel jL_userRole;
    private javax.swing.JPasswordField jP_userPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jT_userName;
    // End of variables declaration//GEN-END:variables
}
